"""Authoritative category guidance returned by /api/v1/operators/categories.

Each entry provides the agent with:
- ``use_for``  : the data-engineering jobs this category is genuinely intended for
- ``not_for``  : common mis-mappings observed in agent traces (anti-patterns)
- ``examples`` : 3-5 representative operator names so the agent has anchors when
                 it issues the follow-up ``list_operators?category=...`` call

The dictionary keys MUST stay in sync with the ``type.level_1`` values of the
operator registry. The endpoint cross-checks against the live registry and
backfills any unknown category with a stub so we never crash if a new category
is introduced upstream.
"""

CATEGORY_GUIDE: dict[str, dict] = {
    "core_text": {
        "use_for": (
            "通用文本→QA / 多跳 QA / 摘要 / 长文本切块生成；prompt-driven 的 "
            "filter / refine / evaluator (PromptedFilter/PromptedRefiner/"
            "PromptedEvaluator)；表格/字段重写用 PandasOperator。"
            "首选这一类做『从原始文本生成 SFT 训练数据』。"
        ),
        "not_for": (
            "**不要**用 SFTGeneratorSeed —— 那个属于 text_sft，是从已有 SFT "
            "种子扩展，而不是从原始文本生成 QA。需要『基础 QA 生成』时直接选 "
            "Text2QAGenerator 或 Text2MultiHopQAGenerator。"
            "也不要用它做 PT 语料质量过滤（去 text_pt）或代码相关任务（去 code）。"
        ),
        "examples": [
            "Text2QAGenerator", "Text2MultiHopQAGenerator",
            "ChunkedPromptedGenerator", "PromptedFilter",
            "PromptedRefiner", "PandasOperator",
        ],
    },
    "general_text": {
        "use_for": (
            "纯文本表面层清洗与统计：基于规则的 Filter（长度、字符比例、"
            "html 实体、URL、PII），N-gram / Hash 去重，BLEU/CIDEr 等无 LLM "
            "评测。**所有不需要 LLM 调用的『通用文本质量过滤』都来这里找**。"
        ),
        "not_for": (
            "需要语义理解的过滤（如『基于 LLM 判断是否为优质问题』）应该用 "
            "core_text 的 PromptedFilter；代码质量过滤去 code；"
            "PT 语料 perplexity/edu-classifier 过滤去 text_pt。"
        ),
        "examples": [
            "CharNumberFilter", "NgramFilter", "HashDeduplicateFilter",
            "HtmlEntityRefiner", "LLMLanguageFilter",
            "ContentNullFilter", "BleuSampleEvaluator",
        ],
    },
    "text_sft": {
        "use_for": (
            "已经有 SFT 数据（instruction / response 列）后做的事："
            "用 Condor / Treeinstruct / Deita / Alpagasus / Superfiltering / "
            "RM / Instag 等方法对 SFT 样本打分、过滤、扩写。"
        ),
        "not_for": (
            "**不要**在『还没生成 QA / instruction』的阶段用这一类。"
            "如果输入只是原始文档，应该先去 core_text（Text2QAGenerator）"
            "或 reasoning（ReasoningQuestionGenerator）生成训练样本，"
            "再回来走 text_sft 做质量评估。SFTGeneratorSeed 也不是『从文本生成 QA』，"
            "它需要既有 SFT 种子。"
        ),
        "examples": [
            "CondorGenerator", "CondorRefiner", "DeitaQualityFilter",
            "AlpagasusFilter", "SuperfilteringFilter", "TreeinstructFilter",
        ],
    },
    "text_pt": {
        "use_for": (
            "**预训练（PT）语料**质量过滤：perplexity 过滤、FineWeb-Edu 分类器、"
            "DebertaV3 质量、CCNet 去重。Phi4QAGenerator 是 PT 风格的 QA 合成。"
        ),
        "not_for": (
            "SFT/QA 数据评估走 text_sft；通用规则去重走 general_text；"
            "推理/数学数据去 reasoning。"
        ),
        "examples": [
            "PerplexityFilter", "FineWebEduFilter", "DebertaV3Filter",
            "CCNetDeduplicateFilter", "Phi4QAGenerator",
        ],
    },
    "reasoning": {
        "use_for": (
            "数学/逻辑推理 CoT 数据：从问题生成 CoT 答案、答案抽取、"
            "题目难度/分类评估、答案 N-gram/format/judge 过滤、"
            "PT 格式转换。**只有当任务明确是 math / step-by-step CoT 时才选这里**。"
        ),
        "not_for": (
            "通用 QA 生成不在这里，去 core_text；代码推理不在这里，去 code；"
            "纯文本清洗不在这里，去 general_text。"
        ),
        "examples": [
            "ReasoningQuestionGenerator", "ReasoningAnswerGenerator",
            "ReasoningQuestionFilter", "ReasoningAnswerFormatterFilter",
            "ReasoningQuestionDifficultySampleEvaluator",
        ],
    },
    "code": {
        "use_for": (
            "代码数据：从代码生成指令、从指令生成代码、代码质量打分、"
            "auto-generated 代码检测、长度/编码异常过滤、sandbox 评估。"
        ),
        "not_for": (
            "自然语言 QA / refine 不在这里；代码相关 SFT 评估也不能直接套通用 "
            "DeitaQuality（去 text_sft 但参数要切换 instruction/response）。"
        ),
        "examples": [
            "CodeInstructionGenerator", "CodeCodeToInstructionGenerator",
            "CodeQualityScoreFilter", "CodeAutoGeneratedFilter",
            "CodeSandboxSampleEvaluator",
        ],
    },
    "conversations": {
        "use_for": (
            "多轮对话/智能体场景的合成与评估：场景抽取/扩写、原子任务/"
            "顺序任务生成、function-calling 对话生成与评估、组合任务过滤。"
        ),
        "not_for": (
            "单轮 QA 不属于这里（去 core_text）；单条 instruction 评估不属于这里"
            "（去 text_sft）。"
        ),
        "examples": [
            "MultiTurnConversationGenerator", "ConsistentChatGenerator",
            "ScenarioExtractGenerator", "FunctionGenerator",
            "FuncCallConversationSampleEvaluator",
        ],
    },
    "knowledge_cleaning": {
        "use_for": (
            "**文档/URL 摄取链路**：File/URL→Markdown 转换（API/Flash/Local 三种），"
            "KBC 切块、清洗、批量 QA 生成。把『PDF/HTML/网页 → 训练数据』的"
            "前几步全部放在这里。"
        ),
        "not_for": (
            "如果输入已经是干净纯文本，跳过这一类，直接去 core_text。"
            "API-only 部署中 KBCChunkGenerator 等可能因依赖缺失不可用，"
            "此时回退到 core_text 的 ChunkedPromptedGenerator。"
        ),
        "examples": [
            "FileOrURLToMarkdownConverterAPI", "FileOrURLToMarkdownConverterFlash",
            "KBCChunkGenerator", "KBCMultiHopQAGeneratorBatch",
            "MathBookQuestionExtract",
        ],
    },
    "agentic_rag": {
        "use_for": (
            "Agentic / 多跳 RAG 训练数据合成：原子任务、宽度/深度 QA 生成与 F1 评估。"
        ),
        "not_for": "普通单跳 QA 走 core_text；多轮对话走 conversations。",
        "examples": [
            "AgenticRAGAtomicTaskGenerator", "AgenticRAGDepthQAGenerator",
            "AgenticRAGWidthQAGenerator", "AgenticRAGQAF1SampleEvaluator",
        ],
    },
    "text2sql": {
        "use_for": "Text2SQL 数据生成与评估：可执行性过滤、组件分类、CoT 投票生成。",
        "not_for": "通用 QA / 推理任务不要走这里。",
        "examples": [
            "Text2SQLCoTVotingGenerator", "SQLExecutabilityFilter",
            "SQLExecutionFilter", "SQLComponentClassifier",
        ],
    },
    "pdf2vqa": {
        "use_for": "PDF→视觉问答数据：MinerU 输入构造、PDF/QA 合并、VQA 格式化、LLM 输出解析。",
        "not_for": "纯文本 QA 走 core_text；普通 OCR/markdown 走 knowledge_cleaning。",
        "examples": [
            "MinerU2LLMInputOperator", "PDF_Merger", "QA_Merger",
            "VQAFormatter", "LLMOutputParser",
        ],
    },
    "core_vision": {
        "use_for": "通用视觉 QA 合成（PromptedVQAGenerator）。",
        "not_for": "PDF 专用流水线去 pdf2vqa。",
        "examples": ["PromptedVQAGenerator"],
    },
    "core_speech": {
        "use_for": "语音转文本（Speech2TextGenerator）。",
        "not_for": "其他模态不属于这里。",
        "examples": ["Speech2TextGenerator"],
    },
    "chemistry": {
        "use_for": "化学领域：从文本抽取 SMILES、SMILES 等价数据集评估。",
        "not_for": "其他领域不属于这里。",
        "examples": [
            "ExtractSmilesFromTextGenerator", "SmilesEquivalenceDatasetEvaluator",
        ],
    },
}


def build_category_response(op_list: list[dict]) -> dict[str, dict]:
    """Return ``{category: {count, use_for, not_for, examples}}``.

    Counts are recomputed from the live registry; use_for/not_for come from
    CATEGORY_GUIDE. Categories present in the registry but missing from the
    guide get an "unknown" stub so the response is never silently lossy.
    """
    counts: dict[str, int] = {}
    for op in op_list:
        cat = (op.get("type") or {}).get("level_1") or "unknown"
        counts[cat] = counts.get(cat, 0) + 1

    result: dict[str, dict] = {}
    for cat, n in counts.items():
        guide = CATEGORY_GUIDE.get(cat, {})
        result[cat] = {
            "count": n,
            "use_for": guide.get("use_for", "(no guidance available)"),
            "not_for": guide.get("not_for", "(no guidance available)"),
            "examples": guide.get("examples", []),
        }
    return result


def valid_categories(op_list: list[dict]) -> list[str]:
    """Categories actually present in the registry (sorted)."""
    seen = set()
    for op in op_list:
        cat = (op.get("type") or {}).get("level_1")
        if cat:
            seen.add(cat)
    return sorted(seen)
